name: Build Flet APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      # ဒီအပိုင်းလေး ထပ်ထည့်ပေးရပါမယ်
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Build APK
        run: |
          pip install flet
          yes | flutter doctor --android-licenses
          flet build apk --android-skip-build-dependency-validation
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/apk/app-release.apk