name: Build Flet APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.7' # Flet version နဲ့ ကိုက်ညီတဲ့ ဗားရှင်း
          channel: 'stable'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flet
        
      - name: Build APK
        run: |
          # Android licenses ကို အော်တို လက်ခံခြင်း
          yes | flutter doctor --android-licenses || true
          # flet build apk ကို interactive မဖြစ်စေဘဲ တိုက်ရိုက် run ခြင်း
          flet build apk --android-skip-build-dependency-validation
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/apk/app-release-*.apk