name: Build Flet APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.7' # Flet version နဲ့ ကိုက်ညီတဲ့ ဗားရှင်း
          channel: 'stable'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flet
        
      - name: Build APK
        run: |
          pip install flet
          yes | flutter doctor --android-licenses || true
          flet build apk
          # ဖိုင်တွေ ဘယ်နေရာမှာ ထွက်လာလဲ သိရအောင် အကုန်ပြခိုင်းမယ်
          echo "Listing all files in build directory:"
          find build -name "*.apk"
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          # ပိုကျယ်ပြန့်တဲ့ path ကို သုံးမယ်
          path: build/**/*.apk
          if-no-files-found: error